### ISSUE TITLE
Updating custom shaders - black screen on launch

### ISSUE THREAD

**Issue by mukulabdagiri** [Rajawali/Rajawali#1885]
#### Rajawali Version or Branch
Master

#### Device and Android Version
Samsung Galaxy 6, Android version 6.0.1

#### Summary
I recently upgraded my project to use latest master version of Rajawali library. It was previously using old 0.9 tag. I updated all my code to use latest library features. But now the project just shows black screen upon launch. So i think the shaders are not set up correctly as I did not update them. Below is the shader code which was working fine with the 0.9 tag. Kindly let me know if the below code will work with the current Rajawali version or if I need to modify it.

#### Steps to Reproduce

```
//BackgroundImage class function to initialize image

public void init(AppRenderer renderer, Context context, int resId)
	{
		try{
	    	FadeMaterial planeMat = new FadeMaterial();
			Bitmap bitmap = BitmapFactory.decodeResource(context.getResources(), resId);
			Texture mutableTexture = new Texture("mutable", bitmap);
			planeMat.addTexture(mutableTexture);
			plane = new Plane(100, 56, 1, 1);
			plane.setScale(PLANE_SCALEFACTOR);
			plane.setMaterial(planeMat);
			plane.setTransparent(true);
			renderer.getCurrentScene().addChild(plane);
		}catch(TextureException e){
			e.printStackTrace();
		}
		
		timer = 0;
		isActive = false;
	}

//FadeMaterial class to fade images

package com.mycompany.myapp;

import org.rajawali3d.materials.Material;
import org.rajawali3d.materials.shaders.FragmentShader;
import org.rajawali3d.materials.shaders.VertexShader;

//previously using - public final class FadeMaterial extends SimpleMaterial
public final class FadeMaterial extends Material {
	
	protected static final String mVShader = 
		    "uniform mat4 uMVPMatrix;\n" +

		    "attribute vec4 aPosition;\n" +
		    "attribute vec2 aTextureCoord;\n" +
		    "attribute vec4 aColor;\n" +

		    "varying vec2 vTextureCoord;\n" +
		    "varying vec4 vColor;\n" +      

		    "void main() {\n" +
		    "   gl_Position = uMVPMatrix * aPosition;\n" +
		    "   vTextureCoord = aTextureCoord;\n" +
		    "   vColor = aColor;\n" +
		    "}\n";

		protected static final String mFShader = 
		    "precision mediump float;\n" +

		    "varying vec2 vTextureCoord;\n" +
		    "uniform sampler2D uDiffuseTexture;\n" +
		    "varying vec4 vColor;\n" +

			"void main() {\n" +
			"   gl_FragColor = texture2D(uDiffuseTexture, vTextureCoord) * vColor;\n" +
			"}\n";

    public FadeMaterial() {
        super(new VertexShader(mVShader), new FragmentShader(mFShader));
        // previously using - super(mVShader, mFShader);
       //setShaders();
        createShaders();
    }
}

```

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
There is a bug in Material.java, it was overwriting vertex and fragment shader with the default strings even when a custom shader string was supplied, a pull request will be submitted. The following is a simplified test case that fails without the change and succeeds with it.
```
    private class CustomShaderRenderer extends Renderer {
        Object3D obj;
        VertexShader vertexShader;
        FragmentShader fragmentShader;

        static final String  vShaderStr =
                "uniform mat4 uMVPMatrix;\n" +
                        "attribute vec4 aPosition; \n" +
                        "void main() \n" +
                        "{ \n" +
                        " gl_Position = uMVPMatrix * aPosition; \n" +
                        "} \n";

        static final String  fShaderStr =
                "precision mediump float; \n" +
                        "void main() \n" +
                        "{ \n" +
                        " gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0); \n" +
                        "}";

        public CustomShaderRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                vertexShader = new VertexShader(vShaderStr);
                fragmentShader = new FragmentShader(fShaderStr);
                Material customMat = new Material(vertexShader, fragmentShader);
                customMat.setColorInfluence(0);
                obj = new Cube(1);
                obj.setMaterial(customMat);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(3,3,3);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
![custommaterialsfix](https://cloud.githubusercontent.com/assets/17471201/25774075/e23b5ed0-323d-11e7-93fd-99df518cc4be.png)

**Comment by contriteobserver** [comment]
Unfortunately, the pull request broke, constructed shaders. Refined the pull request to allow for both supplied string and constructed shaders. (example of constructed shader provide below for testing purposes)
```
    private class ConstructedShaderRenderer extends Renderer {
        Object3D obj;

        public ConstructedShaderRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                VertexShader vertexShader = new VertexShader() {
                    private RMat4 uMVPMatrix;
                    private RVec4 aPosition;

                    @Override
                    public void initialize() {
                        super.initialize();

                        addPrecisionQualifier(DataType.FLOAT, Precision.MEDIUMP);
                        // -- uniforms
                        uMVPMatrix = (RMat4) addUniform(DefaultShaderVar.U_MVP_MATRIX);
                        // -- attributes
                        aPosition = (RVec4) addAttribute(DefaultShaderVar.A_POSITION);
                    }

                    @Override
                    public void main() {
                        GL_POSITION.assign(uMVPMatrix.multiply(aPosition));
                    }
                };

                FragmentShader fragmentShader = new FragmentShader() {
                    @Override
                    public void initialize() {
                        super.initialize();

                        addPrecisionQualifier(DataType.FLOAT, Precision.MEDIUMP);
                    }

                    @Override
                    public void main() {
                        GL_FRAG_COLOR.r().assign(0);
                        GL_FRAG_COLOR.g().assign(1);
                        GL_FRAG_COLOR.b().assign(0);
                        GL_FRAG_COLOR.a().assign(1);
                    }
                };

                Material customMat = new Material(vertexShader, fragmentShader);
                customMat.setColorInfluence(0);
                obj = new Cube(1);
                obj.setMaterial(customMat);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(3, 3, 3);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {
        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
```

**Comment by mukulabdagiri** [comment]
Does the revised version support transparency? I am fading in/out images of pkm format. So would need custom shaders.

**Comment by contriteobserver** [comment]
This change does not alter the GLES transparency implementation. As always, transparency is controlled by the `a` parameter of  `gl_FragColor`

**Comment by jwoolston** [comment]
Resolved via #1896

**Comment by guolei-git** [comment]
你好，在版本1.1.337中这样使用
﻿
﻿
vertexShader = new VertexShader(vShaderStr);
fragmentShader = new FragmentShader(fShaderStr);
Material customMat = new Material(vertexShader, fragmentShader);
customMat.setColorInfluence(0);
obj = new Cube(1);
obj.setMaterial(customMat);
getCurrentScene().addChild(obj);
﻿
仍然无法显示，更换版本1.2.1970是正常的

**Comment by guolei-git** [comment]
Hello, using this in version 1.1.337


vertexShader = new VertexShader(vShaderStr);
fragmentShader = new FragmentShader(fShaderStr);
Material customMat = new Material(vertexShader, fragmentShader);
customMat.setColorInfluence(0);
obj = new Cube(1);
obj.setMaterial(customMat);
getCurrentScene().addChild(obj);

Still unable to display, changing version 1.2.1970 is normal
